server:
  port: 9091
  version: 1.0
spring:
  application:
    name: wink-server
  cloud:
    zookeeper:
      connect-string: localhost:2181
    discovery:
      client:
        health-indicator:
          enabled: true
  messages:
    basename: messages
    encoding: UTF-8